export const data=[
 
    {
      "id": "1",
      "title": "Modern Apartment in the City Center",
      "description": "Spacious and modern apartment located in the heart of the city. Close to shops, restaurants, and public transportation.",
      "price": 20000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1200 sqft",
      "location": "City Center, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "2",
      "title": "Cozy Family Home with Garden",
      "description": "Charming family home with a beautiful garden, perfect for a growing family. Quiet neighborhood with excellent schools nearby.",
      "price": 35000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1800 sqft",
      "location": "Suburbia, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "3",
      "title": "Luxury Villa with Ocean View",
      "description": "Magnificent luxury villa with breathtaking ocean views. Featuring a private pool, spa, and top-of-the-line amenities.",
      "price": 150000,
      "bedrooms": 5,
      "bathrooms": 6,
      "size": "5000 sqft",
      "location": "Seaside, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "4",
      "title": "Studio Apartment in the Artsy District",
      "description": "Quaint studio apartment situated in the vibrant artsy district. Close to galleries, cafes, and public transit.",
      "price": 1200,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "500 sqft",
      "location": "Artsy District, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    },
    {
      "id": "5",
      "title": "Spacious Family House with Mountain Views",
      "description": "Large family house with stunning views of the surrounding mountains. Features a backyard with a BBQ area and play space.",
      "price": 42000,
      "bedrooms": 4,
      "bathrooms": 3,
      "size": "2500 sqft",
      "location": "Mountain View, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "6",
      "title": "Rustic Country Cottage",
      "description": "Charming country cottage nestled in a peaceful rural setting. Perfect for a quiet getaway or weekend retreat.",
      "price": 18000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Country Road, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "7",
      "title": "Stylish Townhouse with Rooftop Deck",
      "description": "Elegant townhouse with a modern design and rooftop deck. Ideal for entertaining and enjoying city views.",
      "price": 55000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1800 sqft",
      "location": "Cityscape, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "8",
      "title": "Lakefront Retreat Cabin",
      "description": "Cozy cabin nestled in a serene lakefront setting. Ideal for nature lovers seeking a peaceful getaway.",
      "price": 18000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "800 sqft",
      "location": "Lakeview, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "9",
      "title": "Modern Condo in a High-rise Building",
      "description": "Sleek and contemporary condo in a luxurious high-rise building. Offers stunning city views and premium amenities.",
      "price": 65000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Skyline Towers, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "10",
      "title": "Quaint Cottage in the Woods",
      "description": "Charming cottage tucked away in a peaceful forest setting. Perfect for a quiet retreat and nature enthusiasts.",
      "price": 12500,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Forest Haven, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "11",
      "title": "Sunny Bungalow with Garden",
      "description": "Bright and sunny bungalow with a lovely garden. Located in a friendly neighborhood with parks and cafes nearby.",
      "price": 28000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1200 sqft",
      "location": "Sunnydale, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "12",
      "title": "Beachfront Condo with Sunset Views",
      "description": "Stylish beachfront condo with breathtaking sunset views. Steps away from sandy shores and beach activities.",
      "price": 38000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Beachside, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "13",
      "title": "Classic Victorian Townhouse",
      "description": "Elegant Victorian townhouse with historical charm. Features original details and a beautiful front porch.",
      "price": 56000,
      "bedrooms": 4,
      "bathrooms": 3,
      "size": "2800 sqft",
      "location": "Victorian Square, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "14",
      "title": "Urban Loft in Historic Building",
      "description": "Industrial-style loft situated in a renovated historic building. Located in a trendy neighborhood with easy access to amenities.",
      "price": 2800,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Historic District, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    },
    {
      "id": "15",
      "title": "Hillside Retreat with Panoramic Views",
      "description": "Stunning hillside retreat offering panoramic views of the city below. Features a private swimming pool.",
      "price": 95000,
      "bedrooms": 4,
      "bathrooms": 4,
      "size": "4000 sqft",
      "location": "Hilltop Estate, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "16",
      "title": "Charming Townhouse with Garden",
      "description": "Lovely townhouse with a lush garden and outdoor seating area. Ideal for those who love gardening.",
      "price": 32000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Garden Terrace, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "17",
      "title": "Spectacular Mansion with Pool",
      "description": "Grand mansion with a luxurious pool and spa. Offers ample space for entertainment and relaxation.",
      "price": 350000,
      "bedrooms": 7,
      "bathrooms": 9,
      "size": "10000 sqft",
      "location": "Mansion Avenue, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "18",
      "title": "Gorgeous Penthouse with River Views",
      "description": "Exquisite penthouse with breathtaking views of the river and city skyline. Features a rooftop terrace.",
      "price": 18000,
      "bedrooms": 4,
      "bathrooms": 4,
      "size": "3500 sqft",
      "location": "Riverfront, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "19",
      "title": "Charming Cottage by the Creek",
      "description": "Adorable cottage located by a peaceful creek. Perfect for nature lovers seeking tranquility.",
      "price": 16500,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "900 sqft",
      "location": "Creek Side, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "20",
      "title": "Sophisticated Condo with City Views",
      "description": "Elegant condo with sophisticated interior design and captivating city views. Close to downtown attractions.",
      "price": 58000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1400 sqft",
      "location": "City View Condos, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "21",
      "title": "Contemporary Beach House",
      "description": "Modern beach house with sleek architecture and direct access to the sandy shores. Ideal for beach lovers.",
      "price": 80000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "2000 sqft",
      "location": "Beachfront, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "22",
      "title": "Charming Colonial Home",
      "description": "Well-maintained colonial-style home with classic features. Offers a cozy and inviting atmosphere.",
      "price": 42000,
      "bedrooms": 4,
      "bathrooms": 3,
      "size": "2200 sqft",
      "location": "Colonial Avenue, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "23",
      "title": "Luxurious Townhouse with Private Garden",
      "description": "Luxury townhouse with high-end finishes and a private garden oasis. Perfect for upscale living.",
      "price": 78000,
      "bedrooms": 3,
      "bathrooms": 3,
      "size": "2800 sqft",
      "location": "Gardenia Terrace, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "24",
      "title": "Charming Bungalow with Vintage Appeal",
      "description": "Cozy bungalow with vintage charm and character. Located in a friendly neighborhood with tree-lined streets.",
      "price": 27500,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1100 sqft",
      "location": "Vintage Lane, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "25",
      "title": "Equestrian Estate with Riding Arena",
      "description": "Elegant equestrian estate with a spacious riding arena and horse facilities. Perfect for horse enthusiasts.",
      "price": 25000,
      "bedrooms": 6,
      "bathrooms": 5,
      "size": "8000 sqft",
      "location": "Equestrian Circle, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "26",
      "title": "Chic City Loft with Industrial Vibes",
      "description": "Stylish loft with industrial vibes and an open-concept layout. Located in a trendy urban neighborhood.",
      "price": 2100,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "800 sqft",
      "location": "Urban Lofts, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    },
    {
      "id": "27",
      "title": "Historic Brownstone with Modern Updates",
      "description": "Historic brownstone meticulously updated with modern amenities. Preserves original architectural details.",
      "price": 95000,
      "bedrooms": 4,
      "bathrooms": 3,
      "size": "2800 sqft",
      "location": "Brownstone Terrace, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "28",
      "title": "Elegant Villa with Pool and Garden",
      "description": "Sophisticated villa with a private pool and lush garden. Offers a serene and luxurious living experience.",
      "price": 1950000,
      "bedrooms": 6,
      "bathrooms": 5,
      "size": "5000 sqft",
      "location": "Elegant Estates, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "29",
      "title": "Rustic Log Cabin in the Woods",
      "description": "Charming log cabin surrounded by nature. Perfect for those seeking a peaceful and rustic retreat.",
      "price": 175000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Woodland Retreat, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "30",
      "title": "Penthouse with Skyline Views",
      "description": "Luxurious penthouse offering stunning views of the city skyline. Features a private rooftop terrace.",
      "price": 750000,
      "bedrooms": 3,
      "bathrooms": 3,
      "size": "3000 sqft",
      "location": "Skyline Towers, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "31",
      "title": "Scenic Mountain Cabin",
      "description": "Cozy mountain cabin with beautiful views of the surrounding wilderness. Ideal for nature lovers.",
      "price": 210000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Mountain Retreat, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "32",
      "title": "Sleek Urban Condo",
      "description": "Modern and sleek urban condo with high-end finishes. Close to downtown and cultural attractions.",
      "price": 430000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1300 sqft",
      "location": "Downtown Core, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "33",
      "title": "Secluded Lakeside Cottage",
      "description": "Charming cottage situated by a serene lakeside. Offers a private and tranquil escape.",
      "price": 185000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "900 sqft",
      "location": "Lakeside Haven, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "34",
      "title": "Contemporary Townhouse with Patio",
      "description": "Sleek and contemporary townhouse with a private patio. Perfect for outdoor gatherings and relaxation.",
      "price": 480000,
      "bedrooms": 3,
      "bathrooms": 3,
      "size": "1800 sqft",
      "location": "Modern Heights, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "35",
      "title": "Historic Estate with Elegant Gardens",
      "description": "Historic estate with elegant gardens and well-preserved architectural details. A true masterpiece.",
      "price": 3500000,
      "bedrooms": 6,
      "bathrooms": 6,
      "size": "6000 sqft",
      "location": "Heritage Lane, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "36",
      "title": "Cozy Cabin with Mountain Views",
      "description": "Cozy cabin with stunning views of the nearby mountains. Perfect for a relaxing retreat.",
      "price": 190000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "900 sqft",
      "location": "Mountain Vista, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "37",
      "title": "Chic Loft in Converted Warehouse",
      "description": "Chic loft space converted from a historic warehouse. Boasts exposed brick walls and open layout.",
      "price": 2500,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "1100 sqft",
      "location": "Warehouse District, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    },
    {
      "id": "38",
      "title": "Spacious Family Home with Pool",
      "description": "Large family home with a private pool and spacious backyard. Ideal for entertaining and relaxation.",
      "price": 560000,
      "bedrooms": 4,
      "bathrooms": 3,
      "size": "2800 sqft",
      "location": "Family Meadows, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "39",
      "title": "Sunny Townhouse with Open Floor Plan",
      "description": "Sunny townhouse with an open floor plan and ample natural light. Located in a quiet and friendly neighborhood.",
      "price": 320000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Sunny Meadows, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "40",
      "title": "Exquisite Mansion with Private Lake",
      "description": "Exquisite mansion with a private lake and expansive grounds. Offers the ultimate luxury living experience.",
      "price": 7500000,
      "bedrooms": 8,
      "bathrooms": 10,
      "size": "12000 sqft",
      "location": "Lakeview Estates, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "41",
      "title": "Artistic Loft with Gallery Space",
      "description": "Artistic loft featuring a dedicated gallery space for showcasing artwork. Perfect for creative individuals.",
      "price": 2800,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "1200 sqft",
      "location": "Arts District, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    },
    {
      "id": "42",
      "title": "Charming Farmhouse with Barn",
      "description": "Charming farmhouse with a traditional red barn. Situated on a picturesque rural property.",
      "price": 340000,
      "bedrooms": 3,
      "bathrooms": 2,
      "size": "1800 sqft",
      "location": "Country Living, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "43",
      "title": "Cozy Cottage with River Views",
      "description": "Cozy cottage with scenic views of the nearby river. Offers a tranquil and serene environment.",
      "price": 220000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Riverwalk, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "44",
      "title": "Spectacular Beachfront Villa",
      "description": "Spectacular villa located directly on the beach. Offers luxury living with mesmerizing ocean views.",
      "price": 2800000,
      "bedrooms": 5,
      "bathrooms": 5,
      "size": "6000 sqft",
      "location": "Beachfront Estates, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "45",
      "title": "Urban Condo with Cityscape Views",
      "description": "Modern condo with panoramic views of the cityscape. Located in a vibrant and lively urban neighborhood.",
      "price": 420000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1400 sqft",
      "location": "Cityscape Condos, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "46",
      "title": "Lakefront Retreat Cabin",
      "description": "Cozy cabin nestled in a serene lakefront setting. Ideal for nature lovers seeking a peaceful getaway.",
      "price": 180000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "800 sqft",
      "location": "Lakeview, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "47",
      "title": "Penthouse with Skyline Views",
      "description": "Luxurious penthouse offering stunning views of the city skyline. Features a private rooftop terrace.",
      "price": 750000,
      "bedrooms": 3,
      "bathrooms": 3,
      "size": "3000 sqft",
      "location": "Skyline Towers, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "48",
      "title": "Quaint Cottage in the Woods",
      "description": "Charming cottage tucked away in a peaceful forest setting. Perfect for a quiet retreat and nature enthusiasts.",
      "price": 125000,
      "bedrooms": 2,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Forest Haven, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "49",
      "title": "Beachfront Condo with Sunset Views",
      "description": "Stylish beachfront condo with breathtaking sunset views. Steps away from sandy shores and beach activities.",
      "price": 380000,
      "bedrooms": 2,
      "bathrooms": 2,
      "size": "1500 sqft",
      "location": "Beachside, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Sale"
    },
    {
      "id": "50",
      "title": "Urban Loft in Historic Building",
      "description": "Industrial-style loft situated in a renovated historic building. Located in a trendy neighborhood with easy access to amenities.",
      "price": 2800,
      "bedrooms": 1,
      "bathrooms": 1,
      "size": "1000 sqft",
      "location": "Historic District, Exampleville",
      "image": "https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-modern-house-plans-1.webp",
      "status": "For Rent"
    }
  ]

